venusproject/cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<uuid:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<uuid:product_id>/', views.full_remove, name='full_remove'),
]

venusproject/shop/urls.py
from django.urls import path
from .views import prod_list, prod_details
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.prod_list, name = 'all_prod_list'),
    path('<uuid:category_id>/', views.prod_list, name = 'products_by_category'),
    path('<uuid:category_id>/<uuid:product_id>/', views.prod_details, name = 'products_details'),
]

venusproject/venusproject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomePageView, AboutPageView
from contact.views import ContactView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', HomePageView.as_view(), name=' '),
    path('home', HomePageView.as_view(), name='home'),
    path('contact', ContactView, name='contact'),
    path('about', AboutPageView.as_view(), name='about'),
    path('involve', include('getinvolved.urls')),
    path('news/', include('news.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

venusproject/home/views.py
from django.views.generic import TemplateView

# Create your views here.
class HomePageView(TemplateView):
    template_name = 'home.html'

venusproject/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block img %}
<div>
    <img src="{% static 'images/AboutPage.jpg' %}" class="img-fluid" id="mainimage">
</div>
{% endblock img %}

{% block linkcss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/about.css' %}">
<title>About</title>
{% endblock linkcss %}

{% block linkJS %}
<script src="{% static 'js/about.js' %}"></script>
{% endblock linkJS %}

{% block content %}
<div class="container-fluid" id="containerfirst">
    <h3>
    What is The Venus Project?
    </h3>
    <p>
    The Venus Project is an organization that proposes a feasible plan of action for social change, one that works towards a peaceful and sustainable global civilization. It outlines an alternative to strive toward where human rights are no longer paper proclamations but a way of life.
    </p>
    <p>
    We propose a fresh, holistic approach – one that is dedicated to human and environmental concerns. It is an attainable vision of a bright and better future, one that is appropriate to the times in which we live, and both practical and feasible for a positive future for all the world’s people.
    </p>
    <p>
        </p><div class="embed-responsive embed-responsive-16by9">
          <iframe title="What is The Venus Project?" width="720" height="405" src="https://www.youtube.com/embed/mX6Y0D8WACA?feature=oembed" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="">
        </iframe>
    </div>
    <p></p>
    <p>
    We advocate an alternative vision unlike any social system that has gone before. Our conclusions are based on years of study and experimental research by many people from various scientific disciplines.
    </p>
    <p>
    We call for a straightforward approach to the redesign of a culture, in which the age-old inadequacies of war, poverty, hunger, debt, environmental degradation and unnecessary human suffering are viewed not only as avoidable, but totally unacceptable.
    </p>	
    <p>
    The Venus Project is a veritable blueprint for the genesis of a new world civilization, one that is based on human concern and environmental reclamation. One fundamental premise is that we work towards having all of the Earth’s resources as the common heritage of all the world’s people. Anything less will simply result in a continuation of the same catalog of problems inherent in the present system.
    </p>
    <p>
    Experience tells us that human behavior can be directed, either toward constructive or destructive activity. This is what The Venus Project is all about – directing our technology and resources toward the positive, for the maximum benefit of people and planet, and seeking out new ways of thinking and living that emphasize and celebrate the vast potential of the human spirit. We have the tools at hand to design and build a future that is worthy of the human potential.
    </p>
    <p>
    The Venus Project presents a bold, new direction for humanity that entails nothing less than the total redesign of our culture. Our proposition is not an attempt to predict what will be done, only what could be done. The responsibility for our future is in our hands, and depends on the decisions that we make today. The greatest resource that is available today is our own ingenuity.
    </p>
    <h3>
    <center>
        <a href="https://www.thevenusproject.com/the-venus-project/">
        Discover The Venus Project
        </a>
    </center>
    </h3>
</div>
{% endblock content %}

venusproject/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html>

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Link css file -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" id="cssLink">
    {% block linkcss %}
    {% endblock linkcss %}
    <!-- Link icon library(font awesome) -->
    <script src="https://kit.fontawesome.com/33f7703c38.js" crossorigin="anonymous"></script>
</head>

<body id="body">
    <div>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top" id="navigationbar">
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'images/Logo.svg' %}" class="img-fluid" alt="Responsive image"
                    style="height: 50px; width: 100%; display: block;">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon">
                </span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active" id="homeBTN">
                        <a class="nav-link" href="{% url 'home' %}">
                            <i class="fa fa-fw fa-home" aria-hidden="true">
                            </i>
                            Home
                            <span class="sr-only">
                                (current)
                            </span>
                        </a>
                    </li>
                    <li class="nav-item" id="contactBTN">
                        <a class="nav-link" href="{% url 'contact' %}">
                            <i class="fa fa-fw fa-envelope" aria-hidden="true">
                            </i>
                            Contact
                        </a>
                    </li>
                    <li class="nav-item" id="aboutBTN">
                        <a class="nav-link" href="{% url 'about' %}">
                            <i class="fa-solid fa-address-card">
                            </i>
                            About us
                        </a>
                    </li>
                    <li class="nav-item" id="involveBTN">
                        <a class="nav-link" href="{% url 'involve_list' %}">
                            <i class="fa-solid fa-bell-concierge">
                            </i>
                            Get Involved
                        </a>
                    </li>
                    <li class="nav-item" id="newsBTN">
                        <a class="nav-link" href="{% url 'news_list' %}">
                            <i class="fa-solid fa-radio">
                            </i>
                            News
                        </a>
                    </li>
                    <li class="nav-item" id="shopBTN">
                        <a class="nav-link" href="{% url 'shop:all_prod_list' %}">
                            <i class="fa-solid fa-shop">
                            </i>
                            Shop
                        </a>
                    </li>
                    {% if item_count > 0 %}
                    <li class="nav-item" id="cartBTN">
                        <a class="nav-link" href="{% url 'cart:cart_detail' %}">
                            <i class="fa-solid fa-cart-shopping">({{item_count}})
                            </i>
                            Cart
                        </a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                    {% else %}
                    <li class="nav-item" id="loginBTN">
                        <a class="nav-link" href="{% url 'login' %}">
                            <i class="fa-solid fa-right-to-bracket">
                            </i>
                            Log in
                        </a>
                    </li>
                    <li class="nav-item" id="signupBTN">
                        <a class="nav-link" href="{% url 'signup' %}">
                            <i class="fa-solid fa-user-plus">
                            </i>
                            Sign up
                        </a>
                    </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li class="nav-item" id="loginBTN">
                        <a class="nav-link" href="#">
                            Welcome, {{ user.username }}
                            <i class="fas fa-user-circle"></i>
                        </a>
                    </li>
                    <li class="nav-item" id="signupBTN">
                        <a class="nav-link" href="{% url 'logout' %}">
                            <i class="fa-solid fa-user-plus">
                            </i>
                            Log out
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        {% block img %}
        {% endblock img %}
        <div id="yoast-breadcrumbs">
            <div class="container-fluid">
                <span>
                    <span id="textyoastadd">
                        <a class="responsive-font1" id="textyoast" href="{% url 'home' %}">
                            Home
                        </a>
                    </span>
                    {% block shopprod %}
                    {% endblock shopprod %}
                </span>
            </div>
        </div>
        {% block content %}
        {% endblock content %}
        <footer class="bg-light text-center text-lg-start" id="footer">
            <div class="text-center p-3" id="content">
                © 2022 The Venus Project | All rights reserved unless otherwise noted.
                <a class="text-dark" href="https://www.thevenusproject.com/">
                    TheVenusProject.com
                </a>
            </div>
        </footer>
    </div>
    {% block linkJS %}
    {% endblock linkJS %}
</body>

</html>

venusproject/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block img %}
<div>
    <img src="{% static 'images/HomePage.jpg' %}" class="img-fluid" id="mainimage">
</div>
{% endblock img %}

{% block linkcss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
<title>WelcomePage</title>
{% endblock linkcss %}

{% block content %}
<div class="container-fluid" id="containerfirst">
    <h3>
        The Venus Project is a non-profit organization that presents a new socio-economic model utilizing
        science and technology toward social betterment to achieve a sustainable civilization of abundance for
        all, without exception.
    </h3>
</div>
<img src="{% static 'images/YoutubeEconomy.jpg' %}" class="img-fluid" href="#Geeks2" data-toggle="modal" id="youtube">
<div class="bs-example">
    <div id="Geeks2" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">
                        Resource Based Economy
                    </h4>
                    <button onclick="var iframe = document.getElementById('Video1'); iframe.src = iframe.src;"
                        type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        x
                    </button>
                </div>
                <div class="embed-responsive embed-responsive-4by3" id="iframe1">
                    <iframe class="embed-responsive-item" title="Introduction"
                        src="https://www.youtube.com/embed/_EkMjTnWk14" allowfullscreen="" id="Video1">
                    </iframe>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <h4 class="responsive-font1">The Venus Project is a non-profit organization that recognizes the important
        connection between global
        resource mismanagement and problems such as war, climate change, poverty, and hunger. In the broader
        context, these are all detrimental results of the current socio-economic operating system. In response to
        these challenges, our organization presents solutions through the holistic application of science and
        technology; two areas in which recent advancements hold the potential to make far-reaching positive impacts.
        However, while technology may succeed in gradually alleviating some of these problems, they cannot be
        resolved by simply addressing symptoms, as we do now, because they are byproducts of a much larger problem.
        Another major issue is that business interests currently require short-term planning and timely returns on
        investments. For these reasons, in addition to our expanded technical approach, our proposals include an
        alternative economic model which overcomes these artificial barriers to planetary wellbeing. Our
        methodologies are designed to realize the full potential of science and technology to achieve social
        betterment for all living systems. We advocate new ways of thinking and living to enable human beings,
        technology, and nature to progress sustainably.</h4>
</div>
{% endblock content %}