venusproject/cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<uuid:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<uuid:product_id>/', views.full_remove, name='full_remove'),
]

venusproject/news/urls.py
from django.urls import path, include
from .views import NewsDeleteView, NewsListView, NewsDetailView, NewsCreateView, NewsUpdateView

urlpatterns = [
    path('', NewsListView.as_view(), name ='news_list'),
    path('search/', include('searchapp.urls')),
    path('<int:pk>/', NewsDetailView.as_view(), name='news_detail'),
    path('new/', NewsCreateView.as_view(), name='news_new'),
    path('<int:pk>/edit/', NewsUpdateView.as_view(), name='news_edit'),
    path('<int:pk>/delete/', NewsDeleteView.as_view(), name='news_delete'),
]

venusproject/searchapp/urls.py
from django.urls import path
from .views import SearchListView

app_name = 'searchapp'

urlpatterns = [

    path('', SearchListView.as_view(), name='searchResult'),

]

venusproject/venusproject/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomePageView, AboutPageView
from contact.views import ContactView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', HomePageView.as_view(), name=' '),
    path('home', HomePageView.as_view(), name='home'),
    path('contact', ContactView, name='contact'),
    path('about', AboutPageView.as_view(), name='about'),
    path('involve', include('getinvolved.urls')),
    path('news/', include('news.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

venusproject/news/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class News(models.Model):
    image = models.ImageField(upload_to='covers/', blank=True)
    title = models.CharField(max_length=200)
    link = models.CharField(max_length=500)

    class Meta:
        ordering = ('pk',)
        verbose_name = 'news'
        verbose_name_plural = 'news'

    def get_absolute_url(self):
        return reverse('news_detail', args=[str(self.id)])

venusproject/news/views.py
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import News
from django.urls import reverse_lazy

# Create your views here.
class NewsListView(ListView):
    paginate_by = 12
    model = News
    template_name = 'news.html'
    context_object_name = "all_news_list"

class NewsDetailView(DetailView):
    model = News
    template_name = 'news_detail.html'

class NewsCreateView(CreateView):
    model = News
    template_name = 'news_new.html'
    fields = ['title', 'link', 'image']

class NewsUpdateView(UpdateView):
    model = News
    template_name = 'news_edit.html'
    fields = ['title', 'image']

class NewsDeleteView(DeleteView):
    model = News
    template_name = 'news_delete.html'
    success_url = reverse_lazy('news_list')

venusproject/news/templates/news.html
{% extends 'base.html' %}
{% load static %}

{% block img %}
<div>
    <img src="{% static 'images/NewsPage1.jpg' %}" class="img-fluid" id="mainimage">
</div>
{% endblock img %}

{% block linkcss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/news.css' %}">
<title>News</title>
{% endblock linkcss %}

{% block linkJS %}
<script src="{% static 'js/news.js' %}"></script>
{% endblock linkJS %}

{% block content %}
<div class="container-fluid" id="containerfirst">
    <center>
        <h3>
            Recent News
        </h3>
        <div class="card">
            <div class="card-body">
                <div class="form-header blue accent-1">
                    <form class="d-flex" action="{% url 'searchapp:searchResult' %}" method="get">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </div>
        <div>
            <a href="{% url 'news_new' %}"> <button type="button" class="btn btn-secondary">New object</button></a>
        </div>
        <div class="row g-2">
            {% for News in all_news_list %}
            <div class="col-md-3">
                <div class="card p-2">
                    <div class="mt-3">
                        <a href="{{ News.link }}" style="text-decoration: none; color: black">
                            {% if News.image %}
                            <img src="{{ News.image.url }}" width="100%">
                            {% endif %}
                            <h6 class="mt-3">
                                {{ News.title }}
                            </h6>
                        </a>
                        <a href="{% url 'news_detail' News.pk %}">
                            <button type="button" class="btn btn-secondary">See details</button>
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        
        <div id="paginator">
            <span class="step-links">
                {% if page_obj.has_previous %}
                <a href="?page=1"><button type="button" class="btn btn-outline-secondary btn-sm">first</button></a>
                <a href="?page={{ page_obj.previous_page_number }}"><button type="button" class="btn btn-outline-secondary btn-sm">previous</button></a>
                {% endif %}
        
                <span class="current">
                   Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
        
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}"><button type="button" class="btn btn-outline-secondary btn-sm">next</button></a>
                    <a href="?page={{ page_obj.paginator.num_pages }}"><button type="button" class="btn btn-outline-secondary btn-sm">last &raquo;</button></a>
                {% endif %}
            </span>
        </div>

    </center>
</div>
{% endblock content %}

venusproject/news/templates/news_delete.html
{% extends 'base.html' %}
{% load static %}

{% block img %}
<div>
    <img src="{% static 'images/NewsPage1.jpg' %}" class="img-fluid" id="mainimage">
</div>
{% endblock img %}

{% block linkcss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/news.css' %}">
<title>News</title>
{% endblock linkcss %}

{% block linkJS %}
<script src="{% static 'js/news.js' %}"></script>
{% endblock linkJS %}

{% block content %}
<center>
    <h1>Delete News</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete this new? "{{ news.title }}"</p>
        <input type="submit" value="Confirm">
    </form>
</center>
{% endblock content%}

venusproject/news/templates/news_detail.html
{% extends 'base.html' %}
{% load static %}

{% block img %}
<div>
    <img src="{% static 'images/NewsPage1.jpg' %}" class="img-fluid" id="mainimage">
</div>
{% endblock img %}

{% block linkcss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/news.css' %}">
<title>News</title>
{% endblock linkcss %}

{% block linkJS %}
<script src="{% static 'js/news.js' %}"></script>
{% endblock linkJS %}

{% block content %}
<center>
<div>
    <p><b>Title:</b> {{ news.title }}</p>
    <p><b>Image:</b> {{ news.image }}</p>
    <p><b>Link:</b> {{ news.link }}</p>
</div>
<a href="{% url 'news_edit' news.pk %}">
    <button type="button" class="btn btn-warning">Edit</button>
</a>
<a href="{% url 'news_delete' news.pk %}">
    <button type="button" class="btn btn-warning">Delete</button>
</a>
</center>
{% endblock content %}

venusproject/news/templates/news_edit.html
{% extends 'base.html' %}
{% load static %}

{% block img %}
<div>
    <img src="{% static 'images/NewsPage1.jpg' %}" class="img-fluid" id="mainimage">
</div>
{% endblock img %}

{% block linkcss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/news.css' %}">
<title>News</title>
{% endblock linkcss %}

{% block linkJS %}
<script src="{% static 'js/news.js' %}"></script>
{% endblock linkJS %}

{% block content %}
<center>
    <h1>Edit News</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
</center>
{% endblock content %}

venusproject/news/templates/news_new.html
{% extends 'base.html' %}
{% load static %}

{% block img %}
<div>
    <img src="{% static 'images/NewsPage1.jpg' %}" class="img-fluid" id="mainimage">
</div>
{% endblock img %}

{% block linkcss %}
<link rel="stylesheet" type="text/css" href="{% static 'css/news.css' %}">
<title>News</title>
{% endblock linkcss %}

{% block linkJS %}
<script src="{% static 'js/news.js' %}"></script>
{% endblock linkJS %}

{% block content %}
<center>
<h1>New news</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
</center>
{% endblock content %}